### ISSUE TITLE
Can this add-on change the background color of the content of the mail?

### ISSUE THREAD

**Issue by qqlovekerry** [Aris-t2/CustomizeMyBird#10]
Hi,
First all, thanks very much for this excellent add-on for Thunderbird!
If possible, could you please tell me whether this add-on has a feature like this? Or maybe it will be added in the future? I want to change the background color fo the region containing the main content of the mail. If it is changeable, maybe some eye-protect color can be used. My screenshot may help to illustrate my need. Please find it in the attachment.
Any help would be much appreciated!
![thunderbird](https://user-images.githubusercontent.com/16799190/46844851-486f0e80-ce0b-11e8-9166-7444e168f0db.png)

**Comment by Aris-t2** [comment]
There is no own option in CMB to change those colors, but you can use this example CSS style on CMBs preference area inside "Custom CSS" textbox to apply own colors:

```css
/* mail content */
html body:not([data-app="thunderbird"]) {
  background: black !important;
  color: white !important;
}

/* mail list background */
#threadContentArea #threadTree treechildren {
  background: black !important;
}

/* mail list active items background */
#threadContentArea #threadTree treechildren::-moz-tree-row(selected),
#threadContentArea #threadTree treechildren::-moz-tree-row(current, focus),
#threadContentArea #threadTree treechildren::-moz-tree-row(selected, focus),
#threadContentArea #threadTree treechildren::-moz-tree-row(dropOn),
#threadContentArea #threadTree treechildren::-moz-tree-row(selected, current, focus),
#threadContentArea #threadTree treechildren::-moz-tree-row(hover),
#threadContentArea #threadTree treechildren::-moz-tree-row(hover, current),
#threadContentArea #threadTree treechildren::-moz-tree-row(hover, selected) {
  background: red !important;
}

/* mail list text color */
#threadContentArea #threadTree treechildren::-moz-tree-cell-text {
  color: white !important;
}

/* mail list active items text color */
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(primary, dropOn),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(selected),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(current, focus),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(selected, focus),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(dropOn),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(selected, current, focus),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(hover),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(hover, current),
#threadContentArea #threadTree treechildren::-moz-tree-cell-text(hover, selected) {
  color: yellow !important;
}
```
