### ISSUE TITLE
[Windows 8] Menu bar glitch and other UI stuff

### ISSUE THREAD

**Issue by MrGlasspoole** [Aris-t2/CustomizeMyBird#13]
Hi,

there's a glitch on the left and right side of the menu bar:
![thunderbird1](https://user-images.githubusercontent.com/2067170/47192746-287da480-d34f-11e8-9434-fd547854a31e.jpg)
Also is it possible that the color from the tab matches the rest? The tab is more white.

Then the old Thunderbrid had a separation line between the menu bar and mail toolbar:
![thunderbird4](https://user-images.githubusercontent.com/2067170/47192826-afcb1800-d34f-11e8-9972-db7a18214822.jpg)
A way to get it back?

And that transparent status bar in TB 60 is horrible:
![thunderbird3](https://user-images.githubusercontent.com/2067170/47192866-0a647400-d350-11e8-9f29-fffab60bd45d.jpg)

Old one was grey:
![thunderbird2](https://user-images.githubusercontent.com/2067170/47192875-17816300-d350-11e8-9dd8-6faa072c66c3.jpg)

This is on Windows 8.1

**Comment by Aris-t2** [comment]
Looks like the menubar issue only occurs on Windows 8, but not on 7 or 10. I fixed it on this test build: CMB_v2.7_201810191.xpi: https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.7

Add this code to this add-ons custom CSS area to restore the line below menubar. (I might add an option for this in the future):

```css
#mail-toolbar-menubar2 {
  border-bottom: 1px solid ThreeDShadow !important;
}
```
_Edit: CMB_v2.7_201810192.xpi already contains this option ;-)_

The statusbar issue does not occur for me on Windows 8 or 10 only on Win7, but this code should fix it for you (add it to custom CSS area too):

```css
.chromeclass-status:not(:-moz-lwtheme) statusbarpanel,
.chromeclass-status:not(:-moz-lwtheme) .statusbar-resizerpanel{
  -moz-appearance: none !important;  
  background: -moz-dialog !important;
  border-left: 0px !important;
  border-right: 0px !important;
  border-bottom: 0px !important;
}
```
