### ISSUE TITLE
[Win8/10] Thunderbird 60+ bottom/status bar color issue

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomizeMyBird#15]
CustomizeMyBird 2.7.1 Win10x64 (default theme)
When General UI > "Main UI & toolbar color: Default" is selected bottom bar inherits tom window color 
Could you please look it this is this an expected behavior?
![tb](https://user-images.githubusercontent.com/32600318/47964579-a8408a00-e044-11e8-8c62-ce8eb8106003.png)

**Comment by Aris-t2** [comment]
Yes, this is the expected behavior (but I have no idea why).
Check with CMB disabled, the result is the same.

**Comment by Aris-t2** [comment]
Try to add something like this to custom CSS area:

```css
	.chromeclass-status:not(:-moz-lwtheme) statusbarpanel,
	.chromeclass-status:not(:-moz-lwtheme) .statusbar-resizerpanel{
	  -moz-appearance: none !important;  
	  background: lightgrey !important;
	  border-left: 0px !important;
	  border-right: 0px !important;
	  border-bottom: 0px !important;
	}
```
