### ISSUE TITLE
[CSS workaround available] Triangle for opening a folder is too small

### ISSUE THREAD

**Issue by gitFrank** [Aris-t2/CustomizeMyBird#16]
Hello, I have many folders with subfolders. The triangles to open are very small. I wonder if it is possible to use the whole space left of the triangle (including the triangle) to open a folder. Or is there an add-on?

**Comment by Aris-t2** [comment]
Please post a screenshot of the "triangle" and "space" you are referring to.

**Comment by gitFrank** [comment]
hope you can understand. :-)


![screenshot_10](https://user-images.githubusercontent.com/5670359/48664720-2ff5b200-eaa3-11e8-80c5-3d31daba595b.jpg)

**Comment by Aris-t2** [comment]
You have a few options to change triangles (aka twistys) space. Add these code snippets to custom CSS area.

This will remove the "space" before twisty:
```css
treechildren::-moz-tree-indentation {
  width: 0px !important;
}
```

This will increase twistys left and right padding:
```css
treechildren::-moz-tree-twisty {
  padding-inline-end: 10px !important;
  padding-inline-start: 10px !important;
}
```

This will increase twistys width:
```css
treechildren::-moz-tree-twisty {
  width: 16px !important;
}
```

**Comment by gitFrank** [comment]
Hi, increase padding-inline-start|end helps me a lot. Thank you for that. *thumb up*
Ideally -moz-tree-twisty would take all the left space. I don't know the structure and classes to be able to play further with CSS. But for now i can good work/live with your solution. :-)

**Comment by Aris-t2** [comment]
Good to hear.

You can at least try to modify the other values to see, if the result fits more your needs. The only way to reduce the space before the twistys was the `treechildren::-moz-tree-indentation` code.

Nur mit dem `treechildren::-moz-tree-indentation` Code wird das Einrücken der Elemente verhindert. Leider sind dann alle Unterordner auf der gleichen Höhe.

**Comment by gitFrank** [comment]
Reduce the space was not the intention. Make the space cklickable to expand the folder was my goal. Because the triangles are so small that I often don't hit them. Then the focus jumps to this folder, but I just wanted to expand it.

Danke für deine Mühe. :-)

**Comment by Aris-t2** [comment]
Understood ;-)

In my tests an additional background color or border also improved the appearance and functionality of the visible space:

```css
treechildren::-moz-tree-twisty {
  padding-inline-end: 10px !important;
  padding-inline-start: 10px !important;
  border-radius: 12px !important;
  border: 1px solid lightgrey !important;
}
treechildren::-moz-tree-indentation {
  width: 4px !important;
}
```

![01](https://user-images.githubusercontent.com/6013569/48702064-3a719200-ebf0-11e8-918a-9fc55f281db3.png)

```css
treechildren::-moz-tree-twisty {
  padding-inline-end: 10px !important;
  padding-inline-start: 10px !important;
  border-radius: 12px !important;
  background: lightgrey !important;
}

treechildren::-moz-tree-indentation {
  width: 4px !important;
}
```
![02](https://user-images.githubusercontent.com/6013569/48702082-40677300-ebf0-11e8-8ae5-00ead987230e.png)

**Comment by gitFrank** [comment]
Yeah, i think with padding and border (without background) my life will be easier.
Problem solved. THANK you!
Thanks for your great Add-on.

**Comment by JYLD** [comment]
I have my folder tree background set to a dark dark gray.  The twisty arrow basically couldn't be seen as a result.  Aris' code for the solution above proved very helpful to me.  Thank you.  I modified Aris' code as follows to make it work for my needs.

```css
treechildren::-moz-tree-twisty {
    padding-inline-end: 5px !important;
    padding-inline-start: 5px !important;
    margin-top: 5px !important;
    margin-bottom: 5px !important;
    margin-right: 8px !important;
    margin-left: 4px !important;
    border-top: 1px solid #FFFFFF !important;
    border-left: 1px solid #FFFFFF !important;
    border-right: 1px solid #000000 !important;
    border-bottom: 1px solid #000000 !important;
    border-radius: 3px 3px 3px 3px !important;
    background: #CDD7DD !important;
}
```

<a href="https://imgur.com/MNOqd2N"><img src="https://i.imgur.com/MNOqd2N.png" title="source: imgur.com" /></a>
