### ISSUE TITLE
[Kubuntu 16.04][Dark-Breeze for gtk Windows theme] - CMB prefwindow - white text on white background

### ISSUE THREAD

**Issue by JPRuehmann** [Aris-t2/CustomizeMyBird#4]
Hello

The Settings Window of CustomizeMyBird is unreadable (White on White).
How can I change that?

I am using Thunderbird 52.7.0, CustomizeMyBird 2.0.7, Kubuntu 16.04 LTS (32Bit)

Thanks,

**Comment by Aris-t2** [comment]
Edit options.css file and change

```css
#CustomizeMyBird_prefwindow {
  background: #fbfbfb;
  font-size: 16px;
}
```

```css
#CustomizeMyBird_prefwindow {
  background: black;
  font-size: 16px;
}
```

Repack and install the add-on. 
I will look into this issue on next update.

---

Could you test this build: [test.zip](https://github.com/Aris-t2/CustomizeMyBird/files/1954874/test.zip)

Or install it from here: https://github.com/Aris-t2/CustomizeMyBird/releases/download/2.0.7/CMB_v2.0.7.1.test.xpi

**Comment by Aris-t2** [comment]
I just have setup **KUbuntu 18.04 x64** (16.04 is way too old) and tested Thunderbird 52.7 and 60 beta. Your issue was not present with any version of CMB 2.0.x. Are you using third party themes or none default ui tweaks?

Looks like this for me:

![kubuntu](https://user-images.githubusercontent.com/6013569/39366837-62981eaa-4a35-11e8-94b2-17747a6e0bbb.png)
(Tb 52)

![kubuntu2](https://user-images.githubusercontent.com/6013569/39366860-6c082598-4a35-11e8-904b-e420e5091a34.png)
(Tb 60)

**Comment by JPRuehmann** [comment]
I am using Dark-Breeze for gtk Windows.
The Edit you send me did not change anything, but after changing the group backgrounds to black to it works.
```
#CustomizeMyBird_prefwindow {
background: black;
font-size: 16px;
}

#CustomizeMyBird_prefwindow #customizemybird_title {
  font-size: 30px;
  text-decoration: underline;
  font-weight: bold;
}

.customizemybird_headline{
  font-size: 20px;
  font-weight: bold;
}

.cmb_groupbox {
  margin-top: 10px;
  margin-bottom: 10px;
}

.cmb_groupbox > hbox {
  border: 1px solid lightgrey;
  margin-top: 1px;
  margin-bottom: 1px;
  background: black;
}
```
Thanks,

**Comment by JPRuehmann** [comment]
![screenshot_20180427_165348](https://user-images.githubusercontent.com/4321829/39369100-ad52d7ea-4a3b-11e8-9c75-646df216aa94.png)

**Comment by Aris-t2** [comment]
How about changing the groupbox > hbox text color to black and keeping the background white?

```css
.cmb_groupbox > hbox {
  border: 1px solid lightgrey;
  margin-top: 1px;
  margin-bottom: 1px;
  background: white;
  color: black;
}
```

https://github.com/Aris-t2/CustomizeMyBird/releases/download/2.0.7/CMB_v2.0.7.2.test.xpi
